# Generated by Django 4.2.4 on 2023-08-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
