# Generated by Django 4.2.4 on 2023-08-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_is_verified_remove_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code_activated',
            field=models.BooleanField(default=False),
        ),
    ]
