# Generated by Django 4.2.4 on 2023-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_email_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outher_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
